# Generated by Django 6.0.5 on 2026-05-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='milestone1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='milestone2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='milestone3',
            field=models.BooleanField(default=False),
        ),
    ]
