# Generated by Django 6.0.5 on 2026-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
