# Generated by Django 6.0.5 on 2026-06-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_application_options_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='bid_resumes/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
