# Generated by Django 6.0.5 on 2026-06-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_project_is_paid_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='plagiarism_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
